using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Yubico.YubiKey.Cryptography;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

namespace powershellYK.support
{
    public class Converter
    {
        public static byte[] StringToByteArray(string hex)
        {
            int numberChars = hex.Length;
            byte[] bytes = new byte[numberChars / 2];
            for (int i = 0; i < numberChars; i += 2)
            {
                bytes[i / 2] = Convert.ToByte(hex.Substring(i, 2), 16);
            }
            return bytes;
        }

        public static string ByteArrayToString(byte[] bytes)
        {
            return BitConverter.ToString(bytes).Replace("-", "");
        }

        // Generated by chatgpt
        public static void ByteSwapPairs(byte[] byteArray)
        {
            // Iterate through the array in steps of 2
            for (int i = 0; i < byteArray.Length; i += 2)
            {
                if (i + 1 < byteArray.Length)
                {
                    // Swap pairs in place
                    byte temp = byteArray[i];
                    byteArray[i] = byteArray[i + 1];
                    byteArray[i + 1] = temp;
                }
                // If there's an odd number of bytes, the last byte remains unchanged
            }
        }

        public static Version IntToVersion(int version)
        {
            byte[] versionBytes = new byte[] { (byte)(version >> 16), (byte)(version >> 8), (byte)version };
            return ByteArrayToVersion(versionBytes);
        }
        public static Version ByteArrayToVersion(byte[] bytes)
        {
            if (bytes.Length != 3)
            {
                throw new ArgumentException("Version must be 3 bytes long");
            }
            return new Version(bytes[0], bytes[1], bytes[2]);
        }

        internal static string RemoveBase64URLSafe(string urlsafe)
        {
            return urlsafe.Replace('-', '+').Replace('_', '/');
        }

        internal static string AddMissingPadding(string base64)
        {
            // Calculate the number of padding characters needed
            int paddingCount = 4 - (base64.Length % 4);
            if (paddingCount != 4)
            {
                base64 += new string('=', paddingCount);
            }
            return base64;
        }

        public static AsymmetricAlgorithm YubiKeyPublicKeyToDotNet(IPublicKey publicKey)
        {
            if (publicKey is RSAPublicKey rsaPublicKey)
            {
                using (RSA rsa = RSA.Create())
                {
                    rsa.ImportSubjectPublicKeyInfo(publicKey.ExportSubjectPublicKeyInfo(), out _);
                    return rsa;
                }
            }
            else if (publicKey is ECPublicKey eccPublicKey)
            {
                using (ECDsa ecc = ECDsa.Create())
                {
                    ecc.ImportSubjectPublicKeyInfo(publicKey.ExportSubjectPublicKeyInfo(), out _);
                    return ecc;
                }
            }
            else if (publicKey is Curve25519PublicKey curve25519PublicKey)
            {
                throw new NotImplementedException("Curve25519PublicKey is not implemented yet.");
            }
            else
            {
                throw new NotSupportedException("Unsupported public key type");
            }
        }
    }
}
