using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace powershellYK.support
{
    public class HexConverter
    {
        public static byte[] StringToByteArray(string hex)
        {
            int numberChars = hex.Length;
            byte[] bytes = new byte[numberChars / 2];
            for (int i = 0; i < numberChars; i += 2)
            {
                bytes[i / 2] = Convert.ToByte(hex.Substring(i, 2), 16);
            }
            return bytes;
        }

        public static string ByteArrayToString(byte[] bytes)
        {
            return BitConverter.ToString(bytes).Replace("-", "");
        }

        // Generated by chatgpt
        public static void ByteSwapPairs(byte[] byteArray)
        {
            // Iterate through the array in steps of 2
            for (int i = 0; i < byteArray.Length; i += 2)
            {
                if (i + 1 < byteArray.Length)
                {
                    // Swap pairs in place
                    byte temp = byteArray[i];
                    byteArray[i] = byteArray[i + 1];
                    byteArray[i + 1] = temp;
                }
                // If there's an odd number of bytes, the last byte remains unchanged
            }
        }

        public static Version IntToVersion(int version)
        {
            byte[] versionBytes = new byte[] { (byte)(version >> 16), (byte)(version >> 8), (byte)version };
            return ByteArrayToVersion(versionBytes);
        }
        public static Version ByteArrayToVersion(byte[] bytes)
        {
            if (bytes.Length != 3)
            {
                throw new ArgumentException("Version must be 3 bytes long");
            }
            return new Version(bytes[0], bytes[1], bytes[2]);
        }
    }
}
