# main.yaml
name: main

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x.x' # Specify the .NET version you're using

    - name: Run dotnet format
      run: dotnet format Module/powershellYK.csproj
      continue-on-error: false

    - name: Check for uncommitted changes
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo "There are uncommitted changes after running dotnet format."
          exit 1
        fi

   - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-restore

    - name: Set up PowerShell 7
      uses: actions/setup-pwsh@v2
      with:
        pwsh-version: '7.x'

    - name: Run Pester Tests
      shell: pwsh
      run: |
        # Import the module
        Import-Module .\Module\bin\module\Release\net8.0\powershellYK.psd1

        # Run Pester tests
        IInvoke-Pester -TagFilter 'Without-Yubikey' -Output Detailed
